# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.resize(840, 250)
        WelcomeWindow.setMinimumSize(QtCore.QSize(840, 250))
        WelcomeWindow.setMaximumSize(QtCore.QSize(840, 250))
        self.centralwidget = QtWidgets.QWidget(WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 170, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(210, 130, 411, 31))
        self.lineEdit.setStyleSheet("font: 75 12pt \"Arial\";")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.labelMessage = QtWidgets.QLabel(self.centralwidget)
        self.labelMessage.setGeometry(QtCore.QRect(280, 80, 271, 41))
        self.labelMessage.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        WelcomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "Connection"))
        self.pushButton.setText(_translate("WelcomeWindow", "CONNECT"))
        self.labelMessage.setText(_translate("WelcomeWindow", "ENTER DATABASE NAME"))
